
/*
 * MCAL_ADC.c
 *
 * Created: 2022-05-06 08:54:12 PM
 *  Author: Eng- Mohamed Mokhtar
 */ 
#include "MCAL_ADC.h"

void (*global_ptr_ADC_CallBack_Function)(void) = NULL;

void MCAL_ADC_INITIATE(U8 Volt_Referencex)
{
	switch(Volt_Referencex)
	{
		case VOLT_AREF_PIN:	//note: Internal 2.56 turned off
		CLR_BIT(REG_ADMUX, ADMUX_REFS1);
		CLR_BIT(REG_ADMUX, ADMUX_REFS1);
		break;
		case VOLT_AVCC_PIN:	//note: Attach the AVCC pin ~ 5V, VREF pin ~ -Cap---i|
		SET_BIT(REG_ADMUX, ADMUX_REFS0);
		CLR_BIT(REG_ADMUX, ADMUX_REFS1);
		break;			//note: Attach the VREF pin ~ -Cap---i|
		case VOLT_2_56_INTERNAL:
		SET_BIT(REG_ADMUX, ADMUX_REFS0);
		SET_BIT(REG_ADMUX, ADMUX_REFS1);
		break;
		default:
		break;
	}
	/***********_ADC_RESULT_ADJUST_**********************************************/
	#if		RESULT_ADJUST == RIGHT_RESULT_ADJUST
	CLR_BIT(REG_ADMUX, ADMUX_ADLAR);
	#elif	RESULT_ADJUST == LEFT_RESULT_ADJUST		//(default)
	SET_BIT(REG_ADMUX, ADMUX_ADLAR);
	#endif
	/***********_ADC_PRESCALER for ADCSRA Register_******************************/
	#if		ADC_PRESCALER			== PRESCALER_DIV_FACTOR_2_
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_4_
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_8_
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_16_
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_32_
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_64_
	CLR_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#elif	ADC_PRESCALER			== PRESCALER_DIV_FACTOR_128_
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS0);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS1);
	SET_BIT(REG_ADCSRA, ADCSRA_ADPS2);
	#endif
	/*==================_Defaults_================================================*/
	CLR_BIT(REG_ADCSRA, ADCSRA_ADATE); //ADC auto_trigering_mode_off
	SET_BIT(REG_ADCSRA, ADCSRA_ADEN);  //ADC Enable
	/*============================================================================*/
}

void MCAL_ADC_Disable(void)
{
	CLR_BIT(REG_ADCSRA, ADCSRA_ADEN);
}

void MCAL_ADC_Channel_Select(U8 ADC_Channel_Name)
{
	switch(ADC_Channel_Name)
	{
		case ADC_CHANNEL_0_:	//PA0
		REG_ADMUX = (((ADC_CHANNEL_0_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_1_:	//PA1
		REG_ADMUX = (((ADC_CHANNEL_1_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_2_:	//PA2
		REG_ADMUX = (((ADC_CHANNEL_2_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_3_:	//PA3
		REG_ADMUX = (((ADC_CHANNEL_3_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_4_:	//PA4
		REG_ADMUX = (((ADC_CHANNEL_4_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_5_:	//PA5
		REG_ADMUX = (((ADC_CHANNEL_5_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_6_:	//PA6
		REG_ADMUX = (((ADC_CHANNEL_6_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		case ADC_CHANNEL_7_:	//PA7
		REG_ADMUX = (((ADC_CHANNEL_7_)&ADMUX_WRITE_RANGE) | (REG_ADMUX & ADMUX_SAFE_RANGE));
		break;
		default:
		break;
	}
}

void MCAL_ADC_Auto_Trigering_Mode(U8 Auto_Trigering_Conig)
{
	switch(Auto_Trigering_Conig)
	{
		case TRIGGERING_DISABLE_MODE:
			CLR_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_FREE_RUNNING_MODE:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
			CLR_BIT(REG_SFIOR, SFIOR_ADTS0);
			CLR_BIT(REG_SFIOR, SFIOR_ADTS1);
			CLR_BIT(REG_SFIOR, SFIOR_ADTS2);
		break;
		case TRIGGERING_SOURCE_ANALOG_COMPARATOR:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
			SET_BIT(REG_SFIOR, SFIOR_ADTS0);
			CLR_BIT(REG_SFIOR, SFIOR_ADTS1);
			CLR_BIT(REG_SFIOR, SFIOR_ADTS2);
		break;
		case TRIGGERING_SOURCE_EXT_INTERRUPT_0_REQUEST:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_TIMER_0_COMPARE_MATCH:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_TIMER_0_OVERFLOW:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_TIMER_1_COMPARE_MATCH_B:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_TIMER_1_OVERFLOW:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		case TRIGGERING_SOURCE_TIMER_1_CAPTURE_EVENT:
			SET_BIT(REG_ADCSRA, ADCSRA_ADATE);
		break;
		default:
		break;
	}
}
/*
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_ANALOG_COMPARATOR
SET_BIT(REG_SFIOR, SFIOR_ADTS0);
CLR_BIT(REG_SFIOR, SFIOR_ADTS1);
CLR_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_EXTERNAL_INTERRUPT_REQUEST_0
CLR_BIT(REG_SFIOR, SFIOR_ADTS0);
SET_BIT(REG_SFIOR, SFIOR_ADTS1);
CLR_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_TIMER_COUNTER_0_COMPARE_MATCH
SET_BIT(REG_SFIOR, SFIOR_ADTS0);
SET_BIT(REG_SFIOR, SFIOR_ADTS1);
CLR_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_TIMER_COUNTER_0_OVERFLOW
CLR_BIT(REG_SFIOR, SFIOR_ADTS0);
CLR_BIT(REG_SFIOR, SFIOR_ADTS1);
SET_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_TIMER_COUNTER_COMPARE_MATCH_B
SET_BIT(REG_SFIOR, SFIOR_ADTS0);
CLR_BIT(REG_SFIOR, SFIOR_ADTS1);
SET_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_TIMER_COUNTER_1_OVERFLOW
CLR_BIT(REG_SFIOR, SFIOR_ADTS0);
SET_BIT(REG_SFIOR, SFIOR_ADTS1);
SET_BIT(REG_SFIOR, SFIOR_ADTS2);
#elif AUTO_TRIGERING_SOURCE == SFIOR_SOURCE_TIMER_COUNTER_1_CAPTURE_EVENT
SET_BIT(REG_SFIOR, SFIOR_ADTS0);
SET_BIT(REG_SFIOR, SFIOR_ADTS1);
SET_BIT(REG_SFIOR, SFIOR_ADTS2);
#endif
#elif	AUTO_TRIGERING_MODE		==   AUTO_TRIGERING_OFF
CLR_BIT(REG_ADCSRA, ADC_ADCSRA_ADATE);
#endif
*/